### ISSUE TITLE
Unable to connecto to login 

### ISSUE THREAD

**Issue by Yasila** [takutoy/nessus-v6-api-sample#1]
Unable to login using the code , it was waiting for a while then threw timeout issue . 

A task was canceled.

![image](https://cloud.githubusercontent.com/assets/20279533/24183332/d0408aca-0eed-11e7-8aa6-321d4f4e90a9.png)

**Comment by takutoy** [comment]
TLS1.2 is required for newer Nessus. Try the following code before login.

`ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`

I updated sample code.

**Comment by Yasila** [comment]
@takutoy Thank you so much , its working fine . great help
